# frozen_string_literal: true

require_relative "cin7_core_api/version"
require_relative "cin7_core_api/errors"
require_relative "cin7_core_api/response"
require_relative "cin7_core_api/redactor"
require_relative "cin7_core_api/connection"
require_relative "cin7_core_api/resources/base"
require_relative "cin7_core_api/resources/me"
require_relative "cin7_core_api/resources/sales"
require_relative "cin7_core_api/resources/credit_notes"
require_relative "cin7_core_api/resources/payments"
require_relative "cin7_core_api/resources/locations"
require_relative "cin7_core_api/resources/accounts"
require_relative "cin7_core_api/resources/bank_accounts"
require_relative "cin7_core_api/resources/customers"
require_relative "cin7_core_api/resources/customer_credits"
require_relative "cin7_core_api/resources/orders"
require_relative "cin7_core_api/resources/invoices"
require_relative "cin7_core_api/resources/manual_journals"
require_relative "cin7_core_api/resources/journals"
require_relative "cin7_core_api/resources/tax_rules"
require_relative "cin7_core_api/resources/webhooks"
require_relative "cin7_core_api/resources/fulfilments"
require_relative "cin7_core_api/resources/picks"
require_relative "cin7_core_api/resources/packs"
require_relative "cin7_core_api/resources/shipments"
require_relative "cin7_core_api/resources/products"
require_relative "cin7_core_api/resources/product_availability"
require_relative "cin7_core_api/resources/carriers"
require_relative "cin7_core_api/client"

module Cin7CoreAPI
end
